import type { ExerciseSeed } from "./types";

// Exercise library seed content for the shoulder slice. Muscle-role assignments
// reflect standard functional anatomy (OpenStax A&P 2e, Ch. 11.5). Exercises are
// described with context rather than as universally "good" or "bad" (spec §8).

const OPENSTAX = "openstax-anp-2e";

export const exercises: ExerciseSeed[] = [
  {
    slug: "dumbbell-overhead-press",
    name: "Dumbbell Overhead Press",
    altNames: "Shoulder press, military press (barbell variant)",
    simpleExplanation: "Pressing weights from shoulder height straight up overhead until the arms are extended.",
    purpose: "Builds pressing strength and overhead capacity in the shoulders and triceps.",
    startingPosition:
      "Stand or sit tall holding a dumbbell in each hand at shoulder height, palms facing forward, elbows under the wrists, core braced.",
    instructions: [
      "Brace your core and keep your ribs down (avoid arching the lower back).",
      "Press both dumbbells up and slightly together until your arms are straight overhead.",
      "Keep the weights over the middle of your body, not drifting forward.",
      "Lower under control back to shoulder height.",
    ],
    breathing: "Breathe out as you press up; breathe in as you lower.",
    cues: "\"Ribs down, squeeze glutes, press to the ceiling.\" Keep the head neutral and let the arms finish near the ears.",
    commonMistakes:
      "Overarching the lower back to help press; flaring elbows too far forward; pressing the weights in front of the head instead of overhead.",
    safety:
      "Requires enough shoulder mobility to reach overhead without arching. If reaching overhead causes pinching or pain, regress or seek assessment.",
    regression: "Seated dumbbell press (more stable) or landmine press (more forgiving angle).",
    progression: "Standing barbell overhead press or single-arm press for more core demand.",
    alternatives: "Landmine press, machine shoulder press.",
    whyItWorks:
      "Pressing overhead loads the deltoids (especially the front fibers) and triceps through a large range while the core and upper back stabilize. It trains a fundamental push pattern used in daily overhead tasks.",
    benefitsWho: "People building general upper-body strength and overhead function.",
    cautionWho:
      "People with painful overhead motion, uncontrolled shoulder impingement symptoms, or those advised by a clinician to avoid overhead loading — modify or substitute.",
    equipment: ["dumbbells"],
    difficulty: "intermediate",
    level: "intermediate",
    movementPattern: "vertical-push",
    setting: "both",
    unilateral: false,
    chain: "open",
    movementPlane: "sagittal",
    status: "source_checked",
    assetSlugs: ["shoulder-region"],
    primaryMuscles: ["deltoid"],
    secondaryMuscles: ["trapezius", "pectoralis-major"],
    stabilizerMuscles: ["supraspinatus", "infraspinatus", "teres-minor", "subscapularis"],
    joints: [{ jointSlug: "glenohumeral-joint", jointAction: "flexion / abduction" }],
    movements: ["shoulder-flexion", "shoulder-abduction"],
    citations: [
      {
        sourceSlug: OPENSTAX,
        claim: "The deltoid (with the anterior fibers prominent) and triceps are principal movers in pressing the arm overhead; rotator cuff muscles stabilize the joint.",
        locator: "Ch. 11.5 Muscles of the Pectoral Girdle and Upper Limbs",
      },
    ],
  },
  {
    slug: "dumbbell-lateral-raise",
    name: "Dumbbell Lateral Raise",
    altNames: "Side raise, lateral fly",
    simpleExplanation: "Lifting light dumbbells out to the sides up to about shoulder height.",
    purpose: "Targets the middle deltoid to build shoulder width and abduction strength.",
    startingPosition: "Stand tall with a light dumbbell in each hand at your sides, elbows very slightly bent.",
    instructions: [
      "Keeping a soft elbow, lift both arms out to the sides.",
      "Stop around shoulder height, leading with the elbows.",
      "Pause briefly, then lower slowly under control.",
    ],
    breathing: "Exhale as you lift; inhale as you lower.",
    cues: "\"Pour the water\" — lead with the elbows, don't shrug the weights up with the traps.",
    commonMistakes: "Using momentum/swinging; shrugging the shoulders; going far above shoulder height with heavy weight.",
    safety: "Use light loads. If the movement pinches at the top, reduce the height or seek assessment.",
    regression: "Perform seated, or one arm at a time with support.",
    progression: "Add a slow eccentric (3–4 s lowering) or a brief pause at the top.",
    alternatives: "Cable lateral raise, machine lateral raise.",
    whyItWorks:
      "The middle deltoid is the main abductor of the arm, so raising the arm to the side directly loads it. Because leverage is high, light weights are plenty.",
    benefitsWho: "People wanting to strengthen and develop the side of the shoulder.",
    cautionWho: "Those with painful abduction or impingement symptoms — reduce range or substitute.",
    equipment: ["dumbbells"],
    difficulty: "beginner",
    level: "beginner",
    movementPattern: "isolation",
    setting: "both",
    unilateral: false,
    chain: "open",
    movementPlane: "frontal",
    status: "source_checked",
    primaryMuscles: ["deltoid"],
    secondaryMuscles: ["supraspinatus", "trapezius"],
    joints: [{ jointSlug: "glenohumeral-joint", jointAction: "abduction" }],
    movements: ["shoulder-abduction"],
    citations: [
      {
        sourceSlug: OPENSTAX,
        claim: "The middle fibers of the deltoid abduct the arm; the supraspinatus assists abduction.",
        locator: "Ch. 11.5 Muscles of the Pectoral Girdle and Upper Limbs",
      },
    ],
  },
  {
    slug: "push-up",
    name: "Push-Up",
    altNames: "Press-up",
    simpleExplanation: "Lowering and pushing your body up from the floor using your arms and chest.",
    purpose: "A bodyweight pushing exercise for the chest, shoulders, and triceps that also trains the core.",
    startingPosition:
      "Hands slightly wider than the shoulders, body in a straight line from head to heels, core and glutes braced (a plank position).",
    instructions: [
      "Bend the elbows to lower your chest toward the floor, keeping the body straight.",
      "Keep the elbows at roughly a 45° angle to the torso (not flared to 90°).",
      "Push the floor away to return to the start, keeping the hips level.",
    ],
    breathing: "Inhale as you lower; exhale as you push up.",
    cues: "\"Long straight body, screw the hands into the floor, elbows back not out.\"",
    commonMistakes: "Sagging or piking the hips; flaring elbows straight out; only lowering a few inches.",
    safety: "Keep the spine neutral. If wrists hurt, use push-up handles or a fist position, or regress.",
    regression: "Incline push-up (hands on a bench) or knee push-up.",
    progression: "Feet-elevated (decline) push-up or tempo push-up.",
    alternatives: "Bench press, machine chest press.",
    whyItWorks:
      "It is a closed-chain push where the chest, front deltoid, and triceps drive the movement while the core resists sagging — training pushing strength and trunk stability together.",
    benefitsWho: "Almost everyone; a scalable staple of upper-body training.",
    cautionWho: "People with wrist pain or those unable to hold a plank without back pain — regress first.",
    equipment: ["bodyweight"],
    difficulty: "beginner",
    level: "beginner",
    movementPattern: "horizontal-push",
    setting: "both",
    unilateral: false,
    chain: "closed",
    movementPlane: "transverse",
    status: "source_checked",
    primaryMuscles: ["pectoralis-major", "deltoid"],
    secondaryMuscles: ["trapezius"],
    stabilizerMuscles: ["subscapularis"],
    joints: [{ jointSlug: "glenohumeral-joint", jointAction: "horizontal adduction / flexion" }],
    citations: [
      {
        sourceSlug: OPENSTAX,
        claim: "The pectoralis major and anterior deltoid are prime movers in horizontal pushing of the arm; it is a compound movement, not a single-muscle exercise.",
        locator: "Ch. 11.5 Muscles of the Pectoral Girdle and Upper Limbs",
      },
    ],
  },
  {
    slug: "band-external-rotation",
    name: "Band External Rotation",
    altNames: "Cable/band shoulder external rotation",
    simpleExplanation: "Rotating the forearm outward against a band while the elbow stays tucked to the side.",
    purpose: "Strengthens the external rotators of the rotator cuff, often under-trained relative to pressing.",
    startingPosition:
      "Stand side-on to an anchored band, elbow bent 90° and tucked against your side, forearm across the body holding the band.",
    instructions: [
      "Keep the elbow pinned to your side (a rolled towel can help).",
      "Rotate the forearm outward, away from your body, keeping the wrist neutral.",
      "Pause, then return slowly to the start.",
    ],
    breathing: "Exhale as you rotate out; inhale on the return.",
    cues: "\"Elbow glued to the ribs, turn the knuckles out, move only at the shoulder.\"",
    commonMistakes: "Letting the elbow drift away from the body; using the whole trunk to twist; going too heavy.",
    safety: "Use light resistance and controlled tempo; this is a stability/health movement, not a max-strength lift.",
    regression: "Reduce band tension or perform lying on your side with a very light dumbbell.",
    progression: "Increase band tension slightly or add range at the shoulder (e.g., 90/90 position).",
    alternatives: "Cable external rotation, side-lying dumbbell external rotation.",
    whyItWorks:
      "The infraspinatus and teres minor externally rotate the arm and help center the humeral head, so targeted external-rotation work supports balanced, healthy shoulder function.",
    benefitsWho: "People who do a lot of pressing/internal-rotation work and want balanced shoulder strength.",
    cautionWho: "Anyone with acute shoulder pain should get assessed before loading the cuff.",
    equipment: ["resistance-band"],
    difficulty: "beginner",
    level: "beginner",
    movementPattern: "rotation",
    setting: "both",
    unilateral: true,
    chain: "open",
    movementPlane: "transverse",
    status: "source_checked",
    primaryMuscles: ["infraspinatus", "teres-minor"],
    stabilizerMuscles: ["deltoid"],
    joints: [{ jointSlug: "glenohumeral-joint", jointAction: "external rotation" }],
    movements: ["shoulder-external-rotation"],
    citations: [
      {
        sourceSlug: OPENSTAX,
        claim: "The infraspinatus and teres minor laterally (externally) rotate the arm at the shoulder.",
        locator: "Ch. 11.5 Muscles of the Pectoral Girdle and Upper Limbs",
      },
    ],
  },
];
