import type { VocabularySeed } from "./types";

// Technical terms with plain-English support for English-as-an-additional-language
// learners (spec section 14). Definitions reflect standard anatomical usage as
// described in OpenStax A&P 2e, Ch. 1.6 "Anatomical Terminology".

export const vocabulary: VocabularySeed[] = [
  {
    slug: "anterior",
    term: "Anterior",
    simpleDefinition: "Toward the front of the body.",
    technicalDefinition: "Nearer to or at the front surface of the body (also called ventral in humans).",
    pronunciation: "an-TEER-ee-or",
    partOfSpeech: "adjective",
    exampleSentence: "The sternum is on the anterior side of the chest.",
    relatedTerms: "ventral",
    confusedTerms: "posterior (the opposite: toward the back)",
  },
  {
    slug: "posterior",
    term: "Posterior",
    simpleDefinition: "Toward the back of the body.",
    technicalDefinition: "Nearer to or at the back surface of the body (also called dorsal).",
    pronunciation: "poss-TEER-ee-or",
    partOfSpeech: "adjective",
    exampleSentence: "The shoulder blades sit on the posterior side of the torso.",
    relatedTerms: "dorsal",
    confusedTerms: "anterior (the opposite: toward the front)",
  },
  {
    slug: "superior",
    term: "Superior",
    simpleDefinition: "Higher up, toward the head.",
    technicalDefinition: "Toward the head or upper part of a structure (also called cranial).",
    pronunciation: "soo-PEER-ee-or",
    partOfSpeech: "adjective",
    exampleSentence: "The shoulders are superior to the hips.",
    confusedTerms: "inferior (the opposite: lower, toward the feet)",
  },
  {
    slug: "inferior",
    term: "Inferior",
    simpleDefinition: "Lower down, toward the feet.",
    technicalDefinition: "Away from the head or toward the lower part of a structure (also called caudal).",
    pronunciation: "in-FEER-ee-or",
    partOfSpeech: "adjective",
    exampleSentence: "The stomach is inferior to the heart.",
    confusedTerms: "superior (the opposite: higher, toward the head)",
  },
  {
    slug: "medial",
    term: "Medial",
    simpleDefinition: "Closer to the middle line of the body.",
    technicalDefinition: "Nearer to the midline (an imaginary vertical line down the center of the body).",
    pronunciation: "MEE-dee-al",
    partOfSpeech: "adjective",
    exampleSentence: "The breastbone is medial to the shoulder.",
    confusedTerms: "lateral (the opposite: toward the side)",
  },
  {
    slug: "lateral",
    term: "Lateral",
    simpleDefinition: "Toward the side, away from the middle.",
    technicalDefinition: "Farther from the midline of the body.",
    pronunciation: "LAT-er-al",
    partOfSpeech: "adjective",
    exampleSentence: "The arms are lateral to the chest.",
    confusedTerms: "medial (the opposite: toward the middle)",
  },
  {
    slug: "proximal",
    term: "Proximal",
    simpleDefinition: "Closer to where a limb attaches to the body.",
    technicalDefinition: "Nearer to the point of origin or attachment of a limb to the trunk.",
    pronunciation: "PROK-sih-mal",
    partOfSpeech: "adjective",
    exampleSentence: "The elbow is proximal to the wrist.",
    confusedTerms: "distal (the opposite: farther from the attachment)",
  },
  {
    slug: "distal",
    term: "Distal",
    simpleDefinition: "Farther from where a limb attaches to the body.",
    technicalDefinition: "Farther from the point of attachment of a limb to the trunk.",
    pronunciation: "DIS-tal",
    partOfSpeech: "adjective",
    exampleSentence: "The hand is distal to the elbow.",
    confusedTerms: "proximal (the opposite: closer to the attachment)",
  },
  {
    slug: "flexion",
    term: "Flexion",
    simpleDefinition: "Bending a joint so the angle between bones gets smaller.",
    technicalDefinition: "A movement that decreases the angle at a joint, usually in the sagittal plane.",
    pronunciation: "FLEK-shun",
    partOfSpeech: "noun",
    exampleSentence: "Bending your elbow to lift a cup is elbow flexion.",
    confusedTerms: "extension (the opposite: straightening a joint)",
  },
  {
    slug: "extension",
    term: "Extension",
    simpleDefinition: "Straightening a joint so the angle between bones gets larger.",
    technicalDefinition: "A movement that increases the angle at a joint, usually in the sagittal plane.",
    pronunciation: "ek-STEN-shun",
    partOfSpeech: "noun",
    exampleSentence: "Straightening your knee is knee extension.",
    confusedTerms: "flexion (the opposite: bending a joint)",
  },
  {
    slug: "abduction",
    term: "Abduction",
    simpleDefinition: "Moving a body part away from the middle of the body.",
    technicalDefinition: "Movement of a limb away from the midline, usually in the frontal plane.",
    pronunciation: "ab-DUK-shun",
    partOfSpeech: "noun",
    exampleSentence: "Raising your arm out to the side is shoulder abduction.",
    confusedTerms: "adduction (the opposite: moving toward the midline)",
  },
  {
    slug: "adduction",
    term: "Adduction",
    simpleDefinition: "Moving a body part toward the middle of the body.",
    technicalDefinition: "Movement of a limb toward the midline, usually in the frontal plane.",
    pronunciation: "add-DUK-shun",
    partOfSpeech: "noun",
    exampleSentence: "Lowering your raised arm back to your side is shoulder adduction.",
    confusedTerms: "abduction (the opposite: moving away from the midline)",
  },
  {
    slug: "agonist",
    term: "Agonist (prime mover)",
    simpleDefinition: "The main muscle that produces a movement.",
    technicalDefinition: "The muscle chiefly responsible for generating a specific joint action.",
    pronunciation: "AG-uh-nist",
    partOfSpeech: "noun",
    exampleSentence: "During a biceps curl, the biceps brachii is the agonist.",
    confusedTerms: "antagonist (the muscle that opposes the movement)",
  },
  {
    slug: "antagonist",
    term: "Antagonist",
    simpleDefinition: "The muscle that opposes or slows the main movement.",
    technicalDefinition: "A muscle that produces the opposite joint action to the agonist and helps control it.",
    pronunciation: "an-TAG-uh-nist",
    partOfSpeech: "noun",
    exampleSentence: "During a biceps curl, the triceps brachii acts as the antagonist.",
    confusedTerms: "agonist (the prime mover)",
  },
];
